development:
  password: xxx
  theme_id: xxx
  store: xxx
  ignore_files:
    - bin/*
    - config/settings_data.json
uat:
  password: xxx
  theme_id: xxx
  store: xxx
  ignore_files:
    - bin/*
    - config/settings_data.json
production:
  password: xxx
  theme_id: xxx
  store: xxx
  timeout: 60s
  readonly: true
  ignore_files:
    - bin/*
    - config/settings_data.json
